### PR TITLE
feat: about page horizontal bar charts

### PR DESCRIPTION
**Pull request by atlisg**

### CODE REVIEW

**Comment by dh4u** [comment]
Hi @atlisg - Just writing a thought here. As I was previewing the changes I was  finding myself very much wanting a US translation because our feeble minds do not process when elections are lost fairly nor kilometers.

**Comment by atlisg** [comment]
> Hi @atlisg - Just writing a thought here. As I was previewing the changes I was finding myself very much wanting a US translation because our feeble minds do not process when elections are lost fairly nor kilometers.

Excellent point. We could add another language, US-English, which would convert all the meters and grams to the appropriate US measurements. Probably best to do that in a separate PR though. I will create a task for it in Asana.

**Comment by dh4u** [comment]
@atlisg - I also find the experience of the tooltip a bit odd. Perhaps if it just went to the center of the bar graph?

Now that I look a bit more - I like the information in the tooltip - I just don't think that there is enough information in the tooltip to merit the tooltip there.  

I understand and like seeing the percentages and I like knowing the actual number as well. I feel like there is enough space to display both by stacking them top to bottom.

**Comment by atlisg** [comment]
> @atlisg - I also find the experience of the tooltip a bit odd. Perhaps if it just went to the center of the bar graph?
> 
> Now that I look a bit more - I like the information in the tooltip - I just don't think that there is enough information in the tooltip to merit the tooltip there.
> 
> I understand and like seeing the percentages and I like knowing the actual number as well. I feel like there is enough space to display both by stacking them top to bottom.

Interesting. Let's discuss on our next dev status call, shall we?

**Comment by atlisg** [comment]
Thanks for the feedback, @dh4u. I agree, the tooltip was redundant so I removed it.

**Pull request merged**
